import { createConstants } from "./index";

export default createConstants(

  "GET_USER_LIST_SUCCESS",
  "GET_USER_LIST_FAILED",
  "GET_USER_LIST_PENDING",

  "GET_POST_LIST_SUCCESS",
  "GET_POST_LIST_FAILED",
  "GET_POST_LIST_PENDING",

  "GET_POST_DETAILS_SUCCESS",
  "GET_POST_DETAILS_FAILED",
  "GET_POST_DETAILS_PENDING",

  "GET_USER_DETAILS_SUCCESS",
  "GET_USER_DETAILS_FAILED",
  "GET_USER_DETAILS_PENDING",

  "UPDATE_USER_DETAILS_SUCCESS",
  "UPDATE_USER_DETAILS_FAILED",
  "UPDATE_USER_DETAILS_PENDING",  

);
